### ISSUE TITLE
Problem with Pool Payouts

### ISSUE THREAD

**Issue by jdoerrer** [scholarshipcoin/scholarshipcoin#2]
I run miner-world.com and it has paid everyone's address but unless they are using a bech32 address that starts with scho its not working which is odd. Is there something corrupt in pool wallet or just something werid with the legacy addresses?  Also I am unable to dumprivkey for same wallet with address that are not bech32. I have not tried segwit.  

Also do you have a discord? telegram?   Just to confirm they do see the balances on the explorer.

**Comment by jdoerrer** [comment]
I wanted to add, I had to set fallbackfee to get wallet to work.

**Comment by scholarshipcoin** [comment]
Hi!


OK so my engineer took a look into it. Here is how it goes:


The minimum payout is 500. The pool will pay once at least 500 worth of coins have been mined and the blocks they mined are unlocked. Every block become unlocked after 20 blocks are mined. Once unlocked the pool system will pay out.


Let me know if you have further questions! 🙂

I do have telegram. Yoi can add me.
Nicholas Dorion




Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by jdoerrer** [comment]
Thats not what I asked, but thanks

**Comment by scholarshipcoin** [comment]
We're looking into it and we will get back to you asap.

Stand by

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by scholarshipcoin** [comment]
Hi again,

Our Tech has found out that the pool seems to do payouts to Legacy or Segwit addresses. You need to switch to Legacy or segwit address (starts with "S").

We are working on a fix for the payouts. Don't worry. I will let you know once the fix is done.

Thanks a lot for your patience.

Nick
________________________________
