### ISSUE TITLE
Wont sync Cant find nodes

### ISSUE THREAD

**Issue by gator6615** [scholarshipcoin/scholarshipcoin#7]
I've installed the latest version says its 3 weeks behind and gets stuck? I've got a large amount of coins coming to this wallet- Now what must I do?

Wallet : 
SXeRFqMJzh9wEQhGfcL3oNYATmvQrK8E5B

**Comment by Original-Tasty** [comment]
Hi,

Is that your wallet on the actual block explorer?
https://explorer.scholarshipcoin.org/address/SXeRFqMJzh9wEQhGfcL3oNYATmvQrK8E5B

Were you before on a previous chain during the tests at the beginning 1 month ago?

Try also first to delete the "peers.dat" file in the blocks folder, and run again the wallet. Let us know if it succeeded to connect by doing so.

Thank you

**Comment by le2Ks** [comment]
> 
> 
> I've installed the latest version says its 3 weeks behind and gets stuck? I've got a large amount of coins coming to this wallet- Now what must I do?
> 
> Wallet :
> SXeRFqMJzh9wEQhGfcL3oNYATmvQrK8E5B

Hi,

Is that your wallet on the actual block explorer?
https://explorer.scholarshipcoin.org/address/SXeRFqMJzh9wEQhGfcL3oNYATmvQrK8E5B

Were you before on a previous chain during the tests at the beginning 1 month ago?

Try also first to delete the "peers.dat" file in the blocks folder, and run again the wallet. Let us know if it succeeded to connect by doing so.

Please join the support on the official discord, it will be a pleasure to help you
https://discord.gg/BjQNWBCTyn


Thank you
